
export interface Question {
    id: number;
    text: string;
}

export const questions: Question[] = [
    { id: 1, text: "Ever argued with a lecturer?"},
    { id: 2, text: "Ever Submitted an Assignment pass the deadline?"},
    { id: 3, text: "Ever wore short skirt/trousers and beg the security to enter?"},
    { id: 4, text: "Ever attended a class that you weren't registerd for?"},
    { id: 5, text: "Ever used ChatGPT to do an entire assignment?"},
    { id: 6, text: "Ever failed a course?"},
    { id: 7, text: "Ever lied to your parents about the credit you're carrying to eat school fees? 😉"},
    { id: 8, text: "Ever faked a receipt to get clearence in the OFFICE? 😉"},
    { id: 9 , text: "Ever argued about grades with a lecturer or TA?"},
    { id: 10, text: "Ever take someone number from the class group chat to text them? 😂"},
    { id: 11, text: "Ever dated someone from campus?"},
    { id: 12, text: "Ever been in a situationship on campus, just to eat chicken 🤣?"},
    { id: 13, text: "Ever skipped class to go to 40-40?"},
    { id: 14, text: "Ever kissed someone from STARZ?"},
    { id: 15, text: "Ever met your lecturer at 40-40 🤔?"},
    { id: 16, text: "Ever been in a talking stage with more than one person at once at STARZ?"},
    { id: 17, text: "Ever had your photo or video taken at 40-40 without you knowing?"},
    { id: 18, text: "Ever pay money for grade only for the teacher to send you C ? 😂"},
    { id: 19, text: "Have your name ever been mentioned in STARZ CONNECT chatroom?"},
    { id: 20, text: "Ever texted someone during class just to flirt?"},
    { id: 21, text: "Ever skipped a test intentionally?"},
    { id: 22, text: "Ever walked from Vamoma to Main Campus instead of riding bike?"},
    { id: 23, text: "Ever ride bike from Main Campus to New Campus? 😆"},
    { id: 24, text: "Ever regretted doing a certain course in STARZ?"},
    { id: 25, text: "Ever pretended to understand something in class without even understanding?"},
    { id: 26, text: "Ever wrote HTML codes on paper in ART 277/205 class? 😂"},
    { id: 27, text: "Ever missed class/test because you were tired from passion chilling night every semester?"},
    { id: 28, text: "Ever cheated during a quiz or test?"},
    { id: 29, text: "Ever attended class just to write your name on the attendance? 😎"},
    { id: 30, text: "Ever faked being sick to skip a presentation?"},
    { id: 31, text: "Ever avoid dressing corporately to skip a presentation?"},
    { id: 32, text: "Ever walked out of the class when the lecturer wasn't watching?"},
    { id: 33, text: "Ever played in any STARZ game at the Invisible Park?"},
    { id: 34, text: "Ever seen a lecturer at Passion/40-40 and pretend not to see them?"},
    { id: 35, text: "Ever ended up in STARZ connect chatroom or STARZ TV page because of something that happened at Passion?"},
    { id: 36, text: "Ever spent your transportation at 40-40?"},
    { id: 37, text: "Ever pretended to be busy on your phone at 40-40 to avoid someone?"},
    { id: 38, text: "Ever had a crush on someone in your department?"},
    { id: 39, text: "Ever collected money from group members in a project because you were the group head?"},
    { id: 40, text: "Ever made 0 in any a quiz/midterm/final in STARZ?"},
    { id: 41, text: "Ever forget your clearence on the day of test?"},
    { id: 42, text: "Ever received Punchline from the workers in the business office 😂?"},
    { id: 43, text: "Ever got a GPA less than 2.0?"},
    { id: 44, text: "Ever been caught spying during midterm/final?"},
    { id: 45, text: "Ever bribed a lecturer?"},
];